import { RemoteOption } from "../types/google/remote-options";

export const SUPPORTED_COUNTRIES: RemoteOption[] = [
  { title: "India", value: "IN" },
  { title: "Bangladesh", value: "BD" },
  { title: "Pakistan", value: "PK" },
  { title: "Vietnam", value: "VN" },
  { title: "United States", value: "US" },
  { title: "Nigeria", value: "NG" },
  { title: "Thailand", value: "TH" },
  { title: "Brazil", value: "BR" },
  { title: "Mexico", value: "MX" },
  { title: "Myanmar", value: "MM" },
  { title: "Democratic Republic of Congo", value: "CD" },
  { title: "Colombia", value: "CO" },
  { title: "Germany", value: "DE" },
  { title: "Nepal", value: "NP" },
  { title: "France", value: "FR" },
  { title: "Turkey", value: "TR" },
  { title: "Netherlands", value: "NL" },
  { title: "Italy", value: "IT" },
  { title: "Cambodia", value: "KH" },
  { title: "United Kingdom", value: "GB" },
  { title: "Argentina", value: "AR" },
  { title: "Uzbekistan", value: "UZ" },
  { title: "Kenya", value: "KE" },
  { title: "Romania", value: "RO" },
  { title: "Spain", value: "ES" },
  { title: "Venezuela", value: "VE" },
  { title: "South Sudan", value: "SS" },
  { title: "Madagascar", value: "MG" },
  { title: "Cameroon", value: "CM" },
  { title: "Poland", value: "PL" },
  { title: "Mozambique", value: "MZ" },
  { title: "Ghana", value: "GH" },
  { title: "Chad", value: "TD" },
  { title: "Sri Lanka", value: "LK" },
  { title: "Angola", value: "AO" },
  { title: "Ecuador", value: "EC" },
  { title: "South Africa", value: "ZA" },
  { title: "Ivory Coast", value: "CI" },
  { title: "Chile", value: "CL" },
  { title: "Canada", value: "CA" },
  { title: "Burkina Faso", value: "BF" },
  { title: "Kazakhstan", value: "KZ" },
  { title: "Malawi", value: "MW" },
  { title: "Laos", value: "LA" },
  { title: "Austria", value: "AT" },
  { title: "Guatemala", value: "GT" },
  { title: "Turkmenistan", value: "TM" },
  { title: "Senegal", value: "SN" },
  { title: "Guinea", value: "GN" },
  { title: "Belgium", value: "BE" },
  { title: "Honduras", value: "HN" },
  { title: "Tajikistan", value: "TJ" },
  { title: "Australia", value: "AU" },
  { title: "Azerbaijan", value: "AZ" },
  { title: "Czech Republic", value: "CZ" },
  { title: "Hungary", value: "HU" },
  { title: "Zimbabwe", value: "ZW" },
  { title: "Serbia", value: "RS" },
  { title: "Slovakia", value: "SK" },
  { title: "Papua New Guinea", value: "PG" },
  { title: "Greece", value: "GR" },
  { title: "Sierra Leone", value: "SL" },
  { title: "Rwanda", value: "RW" },
  { title: "Burundi", value: "BI" },
  { title: "Liberia", value: "LR" },
  { title: "Nicaragua", value: "NI" },
  { title: "Croatia", value: "HR" },
  { title: "Central African Republic", value: "CF" },
  { title: "Paraguay", value: "PY" },
  { title: "Sweden", value: "SE" },
  { title: "Kyrgyzstan", value: "KG" },
  { title: "Belarus", value: "BY" },
  { title: "Albania", value: "AL" },
  { title: "Ireland", value: "IE" },
  { title: "Georgia", value: "GE" },
  { title: "Bosnia & Herzegovina", value: "BA" },
  { title: "New Zealand", value: "NZ" },
  { title: "Finland", value: "FI" },
  { title: "Latvia", value: "LV" },
  { title: "Denmark", value: "DK" },
  { title: "Slovenia", value: "SI" },
  { title: "Norway", value: "NO" },
  { title: "Portugal", value: "PT" },
  { title: "Namibia", value: "NA" },
  { title: "North Macedonia", value: "MK" },
  { title: "Guinea Bissau", value: "GW" },
  { title: "Uruguay", value: "UY" },
  { title: "Fiji", value: "FJ" },
  { title: "Lesotho", value: "LS" },
  { title: "Solomon Islands", value: "SB" },
  { title: "Eswatini", value: "SZ" },
  { title: "Estonia", value: "EE" },
  { title: "Iceland", value: "IS" },
  { title: "Tonga", value: "TO" },
  { title: "Kiribati", value: "KI" },
  { title: "Nauru", value: "NR" },
  { title: "Samoa", value: "WS" },
  { title: "Tuvalu", value: "TV" },
];
